### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by Bobonium** [Rayzilt/Docker-Rspamd#1]
Hey,

it seems you've put a lot of work in here to keep it up to date (same for your Clamav repo https://github.com/Rayzilt/Docker-Clamav)

Have you considered adding a proper License file to your repositories, so that others can make use of them? 

 https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

**Comment by rayzilt** [comment]
Hi Bobonium,

Thank you for pointing that out. I've created a license.
